//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDigester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DefaultEndpointsProtocol=https;AccountName=where2next;AccountKey=5/o577jx5tpc3XZDhQ+PxI9VmK/gd5goRpjRZPNVSspZtIklPp/tuU+JlCNb1VvJZ4I3Wz/qaaNjKf7yTdnPVA==;BlobEndpoint=https://where2next.blob.core.windows.net/;TableEndpoint=https://where2next.table.core.windows.net/;QueueEndpoint=https://where2next.queue.core.windows.net/;FileEndpoint=https://where2next.file.core.windows.net/")]
        public string storageConnectionString {
            get {
                return ((string)(this["storageConnectionString"]));
            }
        }
    }
}
