//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Where2Next
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuburbMaster
    {
        public int PostCode { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string LocLa { get; set; }
        public string LocLong { get; set; }
    }
}
